steps:
  - name: gcr.io/cloud-builders/docker
    args: [build, '--tag=europe-west9-docker.pkg.dev/${PROJECT_ID}/zibou/hugo:${SHORT_SHA}', .]
    dir: blog/hugo-cloudbuild

images: ['europe-west9-docker.pkg.dev/${PROJECT_ID}/zibou/hugo:${SHORT_SHA}']
