steps:
  - name: gcr.io/${PROJECT_ID}/hugo
    dir: blog

  - name: gcr.io/cloud-builders/docker
    args: [build, '--tag=gcr.io/${PROJECT_ID}/blog', .]
    dir: blog

images: ['gcr.io/${PROJECT_ID}/blog']




