steps:
  - name: klakegg/hugo
    dir: blog
    # entrypoint: hugo

  - name: gcr.io/cloud-builders/docker
    args:
      [
        build,
        "--tag=${LOCATION}-docker.pkg.dev/${PROJECT_ID}/zibou/blog:${SHORT_SHA}",
        .,
      ]
    dir: blog

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "${LOCATION}-docker.pkg.dev/${PROJECT_ID}/zibou/blog:${SHORT_SHA}",
      ]
    allowFailure: true

  - name: "bash"
    dir: blog/k8s
    script: |
      #!/usr/bin/env bash
      sed -i 's/<HUGO_BLOG_IMAGE>/'${LOCATION}'-docker.pkg.dev\/'${PROJECT_ID}'\/zibou\/blog:'${SHORT_SHA}'/g' deployment.yaml
      cat deployment.yaml

  # deploy GKE.
  - name: "gcr.io/cloud-builders/gke-deploy"
    dir: blog/k8s
    args:
      - run
      - --filename=.
      - --location=${LOCATION}
      - --cluster=zibou-cluster
    timeout: 600s
options:
  automapSubstitutions: true
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
