
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zibou
spec:
  defaultBackend:
    service:
      name: blog
      port:
        number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  type: NodePort
  ports:
    - port: 80 
      protocol: TCP
      targetPort: 80
  selector:
    app: blog

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
spec:
  selector:
    matchLabels:
      app: blog 
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: blog 
    spec:
      containers:
      - name: blog 
        image: namnguyen107/blog:latest
        ports:
        - containerPort: 80

